// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igofezsvespuomgkkinz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlnb2ZlenN2ZXNwdW9tZ2traW56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODA2NzQsImV4cCI6MjA2Mzg1NjY3NH0.seG1HjOkM6eas_sJYsd8oZElnj4O_DlKIJ7A6gTZSrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);